
include::../_includes/default-attributes.inc.adoc[]
:doctype: book
:toc:
:toclevels: 3
:toc-title: Inhaltsverzeichnis
//:sectnums:
:icons: font
:imagesdir: images

= Betriebsdokumentation: {project-name}
Jakob Häcker (JH)
08.Juli 2021

== Einführung
In diesem Dokument werden wichtig Hinweis und Aleitungen zur Installation und Wartung der Software für die Verwaltung der Partnerhochschulen der HTW Dresden bereitgestellt. Das Ziel ist es dem Administrator alle notwendigen Schritte übersichtlich aufzuzeigen.

Das Hauptaugenmerk unseres Projektes ist es ein Webfrontend unter Nutzung einer gegeben Datenbank zu erstellen.
Von daher werden Datenbank spezifische Erläuterungen nicht vorgenommen.

Detailierte Beschreibungen zu der Bedienung der Software finden sich in der Anwenderdokumentation.

== Systemvoraussetzungen
Um die Software erfolgreich zu installieren sind folgende Voraussetzungen zu erfüllen:

* Software-Vorraussetzungen:
** Verbindung zum Intranet (der HTW) 
** mindestens ein Python3.x Interpreter (getestet mit Python3.8)
** GNU Bash (nur für das Deploy Script)

* innerhalb der HTW:
** SSH-Programm (für UNIX zB. OpenSSH oder für Windows zB. Putty oder WinSCP)
** MariaDB bereitgestellt vom Rechenzentrum der HTW

* Hardware-Vorraussetzungen:

[cols="1,1"]
|===
| Hardware | Virtuelle Maschiene = Mindestanforderung
| CPUs     | 2 (uU. reicht eine) 
| RAM      | 4 GB 
| Speicher (inklusive Platz für Ubuntu) | 35 GB
|===

== Deployment
Die folgenden Absätze beziehen sich nur noch auf auf das Deployment innerhalb des HTW-Netzes.
Mit geringfügien Änderungen im Quelltext ist dies aber auch innerhalb anderer Umgebungen möglich.

Wir gehen davon aus, dass das Rechenzentrum eine MariaDB mit der erforderlichen Datenstruktur bereitstellt.
Wie man das von dem Vorteam verwendete phpMyAdmin benutzt um die Datenbank mit MySQL befehlen zu bearbeiten oder neue Datenbanken zu importieren, verweisen wir wieder auf die Betriebsdokumentation unserers "Vorteams".

== Webserver  
Um ein Webserver innerhalb des HTW-Netzes, mit den oben genannten mindest Anforderungen, zu erhalten muss man das Rechenzentrum der HTW kontaktieren.
Eine andere Möglichkeit besteht darin, einen Server selbst einzurichten. Dies wird allerdings nicht in diesem Dokument behandelt.
Hier wird nur die Funktionsweise und installation auf einer vom Laborbereich der Fakultät Informatik bereitgestellten Virtuellen Maschiene gezeigt.
Aufgrund dessen, dass die VM nur innerhalb des HTW Netzes errichbar ist, ist keine IP sperre über eine .htaccess Datei nötig. Falls diese doch benötigt wird findet sich eine Anleitung in der Betreibsdokumentation des Vorteams im abschnitt 3.1.3.

=== Verbindung auf die Virtuelle Maschiene
Unter Windows empfiehlt sich die Nutzung von WinSCP zum Übertragen von Daten per SSH, Linux Nutzer können die Boardmittel nutzen.

Mit folgenden daten kann eine Verbindung zur Virtuellen Mascheiene Aufgebaut werden:
[cols="1,1"]
|===
| Adresse | seproject@iseproject03
| Passwort| -
| Bemerkung | nur innerhalb des HTW Intra-Netzes erreichbar 
|===

Man befindet sich nun im Home-Verzeichnes der VM und kann nun die Installation der Software vornehemen.

=== Installation der Server-Software
Im folgenden wird vorausgesetzt, dass die Installation in einer Linux Umgebung statt findet.
Eine Addaption auf Windows ist ohne weiters mögich.

* Clonen des GitHub Repositorys
[source, bash]
----
git clone https://github.com/jay-hae/SE-Projekt-I3.git
----

Für das Starten des Servers auf einem Linux System gibt es 2 Möglichkeiten:

* maunelles starten mit Python 
* das Starten und im Hintergrundlaufen lassen über ein System Unit (empfolen)

==== manuelles starten mit Python
// TODO Ordnerstruktur überarbeiten
Dafür ist es nur notwendig in dem Ordner src/ mit folgendem Befehl den Server zu starten:
[source, bash]
----
python3.8 app.py
----
In der Ausgabe des Befehls ist nun die URL zu der Webseite zu finden.

==== Anlegen eines Linux System Units
Eine System Unit ermöglicht es bestimmte Scripte im Hintergrund ausführen zulassen.
Ein System Unit Script ist im geclonten Reposetory unter deploy_scripts/se_webserver.service
Genauer Inforamtionen sind bitte aus dem Internet zu entnehmen. Hier eine Empfehlung: https://wiki.ubuntuusers.de/systemd/Units/[]

* System Unit in das Verzeichnes /etc/systemd/system/ kopieren oder dort selbst anlegen.
[source, bash]
----
cp ./SE-Projekt-I3/deploy_scripts/se_webserver.service /etc/systemd/system/ 
----

* System Unit regestrieren und starten. 
[source, bash]
----
sudo systemctl enable se_webserver.service
sudo systemctl start se_webserver.service
----
Nach "systemctl start" ist der Webserver unter der URL zu erreichen, welche beim manuellen starten des Servers angezeigt wird (siehe Vorheriges Kapitel).

[NOTE]
====
Um den Server wieder zu stoppen:
[source, bash]
----
sudo systemctl stop se_webserver.service
----

Um das Systen Unit wieder zu Entfernen:
[source, bash]
----
sudo systemctl disable se_webserver.service
----
====

== Datenbank

=== Einführung
Die portierte MariaDB beinhaltet Daten zur Darstellung aller Hochschulen, Partnerschaftsverträge, Mentoren der HTW und Statistiken (wobei die Generierung und Anzeige der Statistiken im Verwaltungsfrontend nicht realisiert wurde).

Im Gegensatz zur ursprünglich genutzten Access Datenbank, beinhaltet diese keine personenbezogenen Daten von Studenten und nur noch öffentlich zugängliche Daten von Mentoren der HTW und Ansprechpartner der Hochschulen.

* Dadurch ist kein periodisches Löschen personenbezogener Daten notwendig.

=== Aufbau

In folgendem Diagramm wurden Spalten ohne Beziehungen weggelassen, um eine bessere Übersicht zu erzielen.

[[phys_erm]]
.physisches Entity-Relationship-Diagram
image::../../development/images/physical_erm.svg[]

Die als HTW markierten Tabellen beinhalten Daten der HTW und nicht der Partnerhochschulen.

Durch das mitgelieferte SQL Backup wird die gesamte Struktur mit Daten bereitgestellt. Innerhalb von phpMyAdmin besitzen fast alle Spalten Kommentare zur genaueren Erläuterung.

<<<
// <<< erzwingt neue Seite

=== Tabellen

include::../development/design.adoc[tags=explain_tables]

=== Datensätze außerhalb des Frontends bearbeiten

Wie aus der Tabelle ersichtlich, kann das Verwaltungsfrontend nur einen Teil der Datenbank modifizieren und gar nichts löschen.

Um dennoch beispielsweise falsche Hochschuleinträge zu entfernen werden diese mithilfe von phpMyAdmin gelöscht, dabei beinhaltet keine Beziehung `ON DELETE CASCADE`. Wodurch auch abhängige Datensätze bereinigt werden müssen.

Dies erscheint zunächst unnötig komplex, besonders da das Verwaltungsfrontend die Tabelle _tbl_exchange_ für statistische Zwecke überhaupt nicht nutzt. Hintergrund ist jedoch das wir die Statistik nicht verfälschen möchten da eventuell das Verwaltungsfrontend um Funktionen erweitert wird.

In den FAQs werden bekannte Anwendungsfälle vorgeführt.

== FAQ
