= Design
Jens Rosenkranz <s82099@htw-dresden.de>; Pascal Thielemann <s82101@htw-dresden.de>; Patrick Matthes <s82016@htw-dresden.de >; Nico Rosenkranz <s82122@htw-dresden.de>; Luca Meißner <s82091@htw-dresden.de>; Jakob Häcker <s82048@htw-dresden.de>; Roman Patzig <s82132@htw-dresden.de>; Thanh Ha Khuong <s81983@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Technische Designaspekte
Technische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Funktionsweise einzelner Systemkomponenten haben.

=== Datenbankserver

Es wird ein bereits existenter MariaDB Datenbankserver vom Rechenzentrum genutzt. Der Datenbankserver führt täglich automatische Backups aus. Ebenso liegt die Verantwortlichkeit der Nutzerverwaltung bei dem Rechenzentrum. Dadurch besitzt der DB-Server eine exzellente Verfügbarkeit, Skalierung und Wartbarkeit.

==== Datenbankmodell
Aufgrund der geforderten Kompatibilität mit dem Informationsfrontend ist die Datenbankstruktur weitestgehend vorgeschrieben und festgelegt. Bereits in der Vorgruppe wurden zahlreiche Änderungen im Vergleich zur Access Datenbank vorgenommen, um die Komplexität zu senken und Qualität der Datensätze zu steigern. 

Dabei wurden teils 1:n Beziehungen von Hochschulen zu ihren Ansprechpartnern aufgelöst. 

In folgendem Diagramm wurden Spalten ohne Beziehungen weggelassen, um eine bessere Übersicht zu erzielen.


[[phys_erm]]
.physisches Entity-Relationship-Diagram
image::physical_erm.SVG[]


==== Tabellen

Untenstehend werden alle Tabellen erläutert und aufgezeigt, was innerhalb des Verwaltungsfrontends ermöglicht wird:

• diese hat generell überall Lese- aber nicht Schreibzugriff

+
|===
|Tabelle | Inhalt | Verwaltungsfrontend

|tbl_mentor | Betreuer der Hochschulverträge der HTW | Anlegen, Bearbeiten, Deaktivieren

|tbl_gender | Geschlechterauswahl für Ansprechpersonen und Mentoren | -

|tbl_institute | Partnerhochschule, International office | Auf Informationsfrontend: Anlegen, Bearbeiten, Deaktivieren

|tbl_partnership | Zuweisung eines Partnerschaftstypes (1:n) zu _tbl_institute_ | implizites Anlegen mit Vertrag

|tbl_partnership_type | Definition unterschiedlicher Abkommenstypen | -

|tbl_mobility_agreement | Vertragsinformationen - verweist auf den Mentor und den Vertragstyp / Hochschule in _tbl_partnership_ | Anlegen, Bearbeiten, Deaktivieren

|tbl_mobility_agreement_x_course | "Optionale" Beschränkung der Anzahl von Incoming / Outgoing je Vertrag und Studiengang

Bsp.: Vertrag der Fakultät Informatik für 8 Studenten Incoming/Outgoing -> davon dürfen nur 4 Wirtschaftsinformatik und 4 Informatik sein| Anlegen, Bearbeiten, Deaktivieren

|tbl_faculty | Fakultäten der HTW | -

|tbl_course | Kurse der HTW, genutzt von
_tbl_mobility_agreement_x_course_ und der Statistik | Anlegen, Bearbeiten, Deaktivieren

|tbl_exchange_type | Art des Austausches z.B. Erasmus, Promos, Freemover -> Verwendung für Statistik| -

|tbl_exchange| anonymisierte Daten von Incoming / Outgoing Studenten | Import von Excel Datei zum Hinzufügen von Datensätzen
|===

TIP: Für eine detaillierte Anzeige der Tabellen betrachten Sie bitte die mitgelieferte SQL Backup Datei. Diese ist als Text lesbar und bildet die gesamte Struktur mitsamt Kommentaren ab.

NOTE: Um Probleme mit Modifikationen zu vermeiden, ist allein dem Super-User das Löschen fehlerhafter Datensätze erlaubt. Der Nutzen dieser Funktion sollte jedoch die Ausnahme bilden und nicht die Regel.

==== Views

Für das Informationsfrontend müssen entsprechende Views für jede Tabelle (ausgenommen: `tbl_exchange` und `tbl_exchange_type`) eingerichtet werden. Dabei dürfen nur aktive Verträge angezeigt werden.


==== Verwaltung der Datenbank

Die administrativen Rechte liegen derzeit noch bei einem Mitarbeiter aus dem Rechenzentrum.

=== Webserver

==== Aufbau

Als Webserver dient eine virtuelle Maschine, welche vom Rechenzentrum bereitgestellt wird. Diese ist im Webspace eines Funktionsaccounts aufrufbar. Dort läuft das Backend in Python und das Frontend mithilfe von HTML, CSS und Javascript.

// ==== Authentifizierung im Browser

// Der Punkt Authentifizierung kann noch nicht vollständig berücksichtigt werden, denn es gibt noch keinen konkreten Plan wie mit der Nutzerunterscheidung innerhalb des Softwaresystems umgegangen wird. Man kann aber mit einer Clientseitigen authentifizierung rechnen, das heißt der Nutzer bekommt z.B. einen Cookie gesetzt welcher bei Aufrufen einer Seite mitgeschickt wird.

==== Darstellung

Das User-Interface hat das Ziel intuitiv nutzbar zu sein. Daher ist dieses einfach gestaltet.

Auf jeder Seite

* Nutzung einer Navigationsleiste mit den wichtigsten Links (zu Hochschulen-, Mentorenübersicht)
* Ein Button zum Anlegen neue Daten (Hochschule, Mentor)
* Tabellenansicht zum Anzeigen der Daten
* Ein Button zum Bearbeiten für jeden Datensatz

Die Formularansicht wurde mit Eingabefelder und Labels versehen, um die einfache Zuordnung durch einen Nutzer zu garantieren. Der Speichern-Button ist auch hier Blau hinterlegt, um die Funktion zu verdeutlichen.

//==== Validierung der Daten

//Da eine bloße Validierung von Daten im Frontend unsicher ist, werden eingegebene Daten im Backend validiert. Prinzipiell geschieht das über if-Abfragen im Code, es wird z.B. überprüft, ob der übergebene POST-Parameter existiert, ob er numerisch oder ein leerer String ist.

//Die letzte Instanz der Validierung stellt die Datenbank dar, da nicht valide Formate in einer SQL-Query abgewiesen werden.

=== Synchronisation

Es ist nicht notwendig Daten in einer anderen Datenbank zwischenzuspeichern, weshalb die Website und Datenbank zum Zeitpunkt des Aufrufs immer auf dem aktuellen Stand ist.

Änderungen werden direkt an die Datenbank gesendet, daher ist kein Synchronisationsmechanismus nötig.

=== Schnittstelle zwischen Front- und Backend

Das Übergeben von Daten aus dem Frontend ins Backend wird durch POST-Anfragen geregelt. Verschiedene Javascript-Skripte werten, je nach Anfrage, die Nutzerdaten aus und senden sie an das Backend. Dort werden die einzelnen Parameter der Anfrage ausgewertet und weiterverarbeitet.
Geht es um die reine Darstellung der Webseiten, so nutzt der Client, GET-Anfragen um die entsprechende Website vom Server zurückgeliefert zu bekommen.

Um eine einfache Verarbeitung der, vom Server geschickten Daten, im Frontend vornehmen zu können, haben wir uns für eine übermittlung per JSON-Datei entschieden. Es gibt eine einfache Möglichkeit Pythoneigene Datentypen in eine JSON-Datei zu packen, somit ist der Clientseitige Zugriff auf die Daten ähnlich wie auf dem Server.


== Grafische Designaspekte

Grafische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Darstellungsweise einzelner Systemkomponenten für den Benutzer haben.

Da der Kunde bereits vorher mit Microsoft Access und einem Prototyp gearbeitet hat, wurde bei der Erstellung der Anwendung der Fokus auf eine möglichst nahe Anlehnung der Gestaltung unserer Vorgruppe gelegt.

=== Verwaltungsfrontend

Generell wird für die Darstellung eine Mischung aus Bootstrap und lokalem CSS benutzt.

Die Liste von Hochschulen, Ländern, Vertragstypen etc. werden beim Laden der Seite durch Javascript-Skripte geladen zusätzlich bei der Auswahl eines Filters aktualisiert. Sie sind in einer Tabelle angeordnet.

Das Bearbeitungsformular wird als (Popup-)Modal über dem Inhalt der Seite dargestellt. Dieses ist am Anfang des Seitenaufrufs versteckt und wird nur angezeigt, wenn der Bearbeiten- oder Erstellen-Button betätigt wurde.

