= Design: {project-name}
Jens Rosenkranz <s82099@htw-dresden.de>; Pascal Thielemann <s82101@htw-dresden.de>; Patrick Matthes <s82016@htw-dresden.de >; Nico Rosenkranz <s82122@htw-dresden.de>; Luca Meißner <s82091@htw-dresden.de>; Jakob Häcker <s82048@htw-dresden.de>; Roman Patzig <s82132@htw-dresden.de>; Thanh Ha Khuong <s81983@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Technische Designaspekte
Technische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Funktionsweise einzelner Systemkomponenten haben.

=== Datenbankserver

Es wird ein bereits existenter MariaDB Datenbankserver vom Rechenzentrum genutzt. Der Datenbankserver führt täglich automatische Backups aus. Ebenso liegt die Verantwortlichkeit der Nutzerverwaltung bei dem Rechenzentrum. Dadurch besitzt der DB-Server eine exzellente Verfügbarkeit, Skalierung und Wartbarkeit.

==== Datenbankmodell
Aufgrund der geforderten Kompatibilität mit dem Informationsfrontend ist die Datenbankstruktur weitestgehend vorgeschrieben und festgelegt. Bereits in der Vorgruppe wurden zahlreiche Änderungen im Vergleich zur Access Datenbank vorgenommen, um die Komplexität zu senken und Qualität der Datensätze zu steigern. 

Dabei wurden teils 1:n Beziehungen von Hochschulen zu ihren Ansprechpartnern aufgelöst. 

In folgendem Diagramm wurden Spalten ohne Beziehungen weggelassen, um eine bessere Übersicht zu erzielen.

(Platzhalter Datenbankmodell)

==== Tabellen

Untenstehend werden alle Tabellen erläutert und aufgezeigt, was innerhalb des Verwaltungsfrontends ermöglicht wird:

• diese hat generell überall Lese- aber nicht Schreibzugriff

+
|===
|Tabelle | Inhalt | Verwaltungsfrontend

|tbl_mentor | Betreuer der Hochschulverträge der HTW | Anlegen, Bearbeiten, Deaktivieren

|tbl_gender | Geschlechterauswahl für Ansprechpersonen und Mentoren | -

|tbl_institute | Partnerhochschule, International office | Auf Informationsfrontend: Anlegen, Bearbeiten, Deaktivieren

|tbl_partnership | Zuweisung eines Partnerschaftstypes (1:n) zu _tbl_institute_ | implizites Anlegen mit Vertrag

|tbl_partnership_type | Definition unterschiedlicher Abkommenstypen | -

|tbl_mobility_agreement | Vertragsinformationen - verweist auf den Mentor und den Vertragstyp / Hochschule in _tbl_partnership_ | Anlegen, Bearbeiten, Deaktivieren

|tbl_mobility_agreement_x_course | "Optionale" Beschränkung der Anzahl von Incoming / Outgoing je Vertrag und Studiengang

Bsp.: Vertrag der Fakultät Informatik für 8 Studenten Incoming/Outgoing -> davon dürfen nur 4 Wirtschaftsinformatik und 4 Informatik sein| Anlegen, Bearbeiten, Deaktivieren

|tbl_faculty | Fakultäten der HTW | -

|tbl_course | Kurse der HTW, genutzt von
_tbl_mobility_agreement_x_course_ und der Statistik | Anlegen, Bearbeiten, Deaktivieren

|tbl_exchange_type | Art des Austausches z.B. Erasmus, Promos, Freemover -> Verwendung für Statistik| -

|tbl_exchange| anonymisierte Daten von Incoming / Outgoing Studenten | Import von Excel Datei zum Hinzufügen von Datensätzen
|===

NOTE: Um Probleme mit Modifikationen zu vermeiden, ist allein dem Super-User das Löschen fehlerhafter Datensätze erlaubt. Der Nutzen dieser Funktion sollte jedoch die Ausnahme bilden und nicht die Regel.

==== Views 

Für das Informationsfrontend müssern entsprechende Views den Anforderungen entsprechend für fast jede Tabelle eingerichtet werden. Ausgenommen: tbl_exchange und tbl_exchange_type

Dabei dürfen nur aktive Verträge berücksichtigt werden.


==== Verwaltung der Datenbank

Zur administrativen Verwaltung der Datenbank wird ein Super-User eingerichtet. Dieser hat - neben dem normalen User - die notwendigen Berechtigungen falsch angelegte Daten zu löschen.

=== Webserver

(ToDo)

=== Synchronisation

Es ist nicht notwendig Daten in einer anderen Datenbank zwischenzuspeichern, weshalb die Website und Datenbank zum Zeitpunkt des Aufrufs immer auf den aktuellen Stand ist.

Auf der anderen Seite werden Änderungen direkt an die Datenbank gesendet, daher ist kein Synchronisationsmechanismus nötig.

=== Schnittstelle zwischen Front- und Backend

(ToDo)

== Graphische Designaspekte

Graphische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Darstellungsweise einzelner Systemkomponenten für den Benutzer haben.

Da der Kunde bereits vorher mit Microsoft Access und einem Prototypen gearbeitet hatte, wurde bei der Erstellung der Anwendung der Fokus auf eine möglichst nahe Anlehnung der Gestaltung unserer Vorgruppe gelegt.

=== Verwaltungsfrontend

(To-Do)
