== Use-Case: Anlegen von Mentoren (UC05)

=== Kurzbeschreibung
Eine Arbeitskraft der SI legt einen neuen Metoren an.

=== Kurzbeschreibung der Akteure
==== Mitarbeiter*Innen Stabsstelle Internationales
Sind bei der Stabsstelle Internationales angestellt. Sie möchten innerhalb der Verwaltungsanwendung neue Mentoren erzeugen.

=== Vorbedingungen
Die Arbeitskraft hat sich erfolgreich eingeloggt. (UC01) und hat uneingeschränkten Zugriff auf die Verwaltungsanwendung.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

1. Der Use Case beginnt, wenn MSI die Funktion zum Anlegen eines neuen Mentoren ausgewählt hat.
2. System öffnet ein externes Fenster zum Eingeben aller Mentorenattribute (ID, FakultätsID, Geschlecht, Titel, Name, Homepage, Status).
3. WHILE Eingabe nicht validiert
3.1 IF MSI beendet den Vorgang
3.1.1 Externe Eingabemaske wird geschlossen.
3.1.2 Use Case wird beendet.
3.2 MSI gibt Attributwerte ein
3.3 System überprüft Eingabe auf Gültigkeit
4. MSI wählt Option zum Anlegen des Mentoren
5. System legt Mentor in der Datenbank an
6. Eingabemaske wird geschlossen

=== Wesentliche Szenarios
==== MSI legt erfolgreich einen neuen Mentoren an
. <Szenario 1.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 1.2, Die Funktion zum Anlegen eines neuen Mentoren wird gewählt.>
. <Szenario 1.3, Die Arbeitskraft trägt die Daten in die Eingabemaske ein.>
. <Szenario 1.4, Es handelt sich um valide Daten, somit wird der Mentor in der Datenbank angelegt.>

=== Daten konnten nicht validiert werden, Mitarbeiter beendet den Vorgang
. <Szenario 2.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 2.2, Die Funktion zum Anlegen eines neuen Mentoren wird gewählt.>
. <Szenario 2.3, Die Arbeitskraft trägt die Daten in die Eingabemaske ein.>
. <Szenario 2.4, Das System erkennt eine fehlerhafte Eingabe>
. <Szenario 2.5, Die Arbeitskraft beendet den Use Case eigenständig>

=== Nachbedingungen
Nach erfolgreichem Abschluss des Use Cases lautet der Ist-Zustand wie folgt:
* Der Datenbank wurde ein valides Objekt in der richtigen Tabelle hinzugefügt.

=== Besondere Anforderungen
==== <Zugangssperre>
Der Zugang zum System darf nur innerhalb des HTW-Netzes erfolgen, eine IP-Sperre ist erforderlich.

==== <Gültigkeitsregeln>
Die entsprechenden Abhängigkeiten und Datentypen innerhalb der bestehenden Datenbank müssen eingehalten werden.

==== <Benutzeroberfläche>
Das Interface welches, zum Eingeben der Objektattribute und dem speichern der Mentoren benutzt werden soll, muss als externes Fenster auf der Seite geöffnet werden.