== Use-Case: Löschen von Mentoren (UC07)

=== Kurzbeschreibung
Eine Leitung der Stabsstelle Internationales löscht einen Mentoren.

=== Kurzbeschreibung der Akteure
==== Mitarbeiter*Innen Stabsstelle Internationales
Sind die Leitung der Stabsstelle Internationales. Sie möchten ein Mentoren aus der Datenbank löschen.

=== Vorbedingungen
Die Leitung hat uneingeschränkten Zugriff auf die gesamte Verwaltungsanwendung. Die Mitarbeiter der SI haben keinen Zugriff auf den Löschvorgang.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

1. Der Use Case beginnt, wenn MSI die Funktion zum Löschen eines Mentoren ausgewählt hat  
2. Das System gibt einen Warnhinweis aus und fordert erneute Bestätigung des Vorhabens
2.1 IF Nutzer gibt keine erneute Bestätigung
2.1.1 Mentor wird nicht gelöscht
2.1.2 Der Use Case wird beendet
2.2 System prüft ob Mentor gelöscht werden kann
2.3 IF System gibt keine Löscherlaubnis
2.3.1 Löschvorgang wird beendet.
2.3.2 Use Case wird beendet 
3. Das System löscht den gewählten Mentoren aus der Datenbank

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.


==== Mentor wurde erfolgreich gelöscht
. <Szenario 1.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 1.2, Es wird für einen Mentoren die Löschfunktion ausgewählt.>
. <Szenario 1.3, Das System prüft ob der Mentor gelöscht werden kann und liefert ein positives Feedback.>
. <Szenario 1.4, System fragt ob Löschaktion wirklich ausgeführt werden soll.>
. <Szenario 1.5, Mitarbeiter bestätigt, der Mentor wird aus der Datenbank entfernt.>

=== Mentor konnte nicht gelöscht werden
. <Szenario 1.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 1.2, Es wird für einen Mentoren die Löschfunktion ausgewählt.>. 
. <Szenario 1.3, Das System prüft ob der Mentor gelöscht werden kann.>
. <Szenario 1.4, Das System erkennt noch bestehende Abhängigkeiten weswegen der Mentor nicht gelöscht werden kann.>
. <Szenario 1.5, Es erscheint eine Fehlermeldung. Der Löschvorgang wird automatisch abgebrochen und der Use Case beendet>

=== Nachbedingungen
Nach erfolgreichem Abschluss des Use Cases lautet der Ist-Zustand wie folgt:
- Der zu löschende Mentor wurde aus der entsprechenden Relation in der Datenbank entfernt.


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Zugangssperre>
Der Zugang zum System darf nur innerhalb des HTW-Netzes erfolgen, eine IP-Sperre ist erforderlich.

==== <Gültigkeitsregeln>
Die entsprechenden Abhängigkeiten und Datentypen innerhalb der bestehenden Datenbank müssen eingehalten werden.
