//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).

== Use-Case: Bearbeiten von Hochschulen (UC03)

=== Kurzbeschreibung
Eine Arbeitskraft der Stabsstelle Internationales verändert Attribute der Hochschule

=== Kurzbeschreibung der Akteure
==== Mitarbeiter*Innen Stabsstelle Internationales
Sind bei der Stabsstelle Internationales angestellt. Sie möchten Bestandsdaten eines Objektes anpassen.

=== Vorbedingungen
Die Arbeitskraft hat uneingeschränkten Zugriff auf die Verwaltungsanwendung.


=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

1. Der Use Case beginnt, wenn MSI die Funktion zum Bearbeiten einer Hochschule ausgewählt hat  
2. System öffnet eine externe Eingabemaske in der alle Attribute der Hochschule angezeigt und geändert werden können
3. MSI ändert Attribute der Hochschule
3.1 WHILE Eingabe nicht validiert
3.1.1 Ausgeben einer Fehlermeldung
3.1.2 Löschen der letzten Eingabe
3.1.3 MSI wiederholt Eingabe
4. MSI wählt Option zum Speichern der Änderungen aus
5. System überschreibt Bestandsdaten der Hochschule.

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.

==== Erfolreiche Änderung der Daten
. <Szenario 1.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 1.2, Die Funktion zum Ändern einer bestehender Hochschule wird gewählt.>
. <Szenario 1.3, Das System öffnet eine externe Eingabemaske>
. <Szenario 1.4, Die Arbeitskraft bekommt eine Übersicht der Bestandsdaten der Hochschule und kann diese verändern>
. <Szenario 1.5, Das System hat die Änderungen validiert.>
. <Szenario 1.6, Die Arbeitskraft wählt die Option zum speichern aus, die Bestandsdaten der Hochschule werden Datenbankseitig überschrieben.>

=== Ändern der Daten ist gescheitert, Arbeitskraft bricht den Vorgang ab
. <Szenario 1.1: Die Arbeitskraft ist erfolreich in die Anwendung eingeloggt.>
. <Szenario 1.2, Die Funktion zum Ändern einer bestimmten Hochschule wird gewählt.>
. <Szenario 1.3, Das System öffnet eine externe Eingabemaske>
. <Szenario 1.4, Die Arbeitskraft bekommt eine Übersicht der Bestandsdaten der Hochschule und kann diese verändern>
. <Szenario 1.5, Die geplanten Änderungen konnten nicht validiert werden>
. <Szenario 1.6, Das System gibt eine Fehlermeldung aus, daraufhin beendet die Arbeitskraft den Vorgang selbstständig.>

=== Nachbedingungen
Nach erfolgreichem Abschluss des Use Cases lautet der Ist-Zustand wie folgt:
* Die Bestandsdaten der jeweiligen Hochschule wurden aktualisiert. Sie entsprechen den kürzlich eingegebenen Daten. 


=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.

==== <Zugangssperre>
Der Zugang zum System darf nur innerhalb des HTW-Netzes erfolgen, eine IP-Sperre ist erforderlich.

==== <Gültigkeitsregeln>
Die entsprechenden Abhängigkeiten und Datentypen innerhalb der bestehenden Datenbank müssen eingehalten werden.

==== <Benutzeroberfläche>
Das Interface welches, zum Eingeben der Objektattribute und dem speichern des Objektes benutzt werden soll, muss als externes Fenster auf der Seite geöffnet werden.
