
= Vision: {project-name}
Jens Rosenkranz <s82099@htw-dresden.de>; Pascal Thielemann <s82101@htw-dresden.de>; Patrick Matthes <s82016@htw-dresden.de >; Nico Rosenkranz <s82122@htw-dresden.de>; Luca Meißner <s82091@htw-dresden.de>; Jakob Häcker <s82048@htw-dresden.de>; Roman Patzig <s82132@htw-dresden.de>; Thanh Ha Khuong <s81983@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Um das Projekt im groben einordnen zu können, ist es wichtig sich mit den Rahemenbedingungen des Projektes vertraut zu machen.
Dafür werden in dem Dokument das Grundproblem, Stakeholder und wesentliche Anforderungen definiert.
Die Details, wie die Webanwendung diese Anforderungen erfüllt, werden in der Use-Case und
Supplementary Specification beschrieben.


=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben. Des Weitern werden die Stakholder identifiziert und die Grundproblematik
der Auftraggeber benannt.



=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System der Webanwendung zur Verwaltung 
der Datenbank der Stabsstelle Internationales, das von Team I3 entwickelt wird. 

Das System wird es den Mitarbeitern der Stabsstelle Internationales erlauben, innerhalb einer Webanwendung die Hochschulpartnerschaften sowie die Austauschprogramme für Studierende und Hochschullehrer zu verwalten und Statistiken und Berichte aus diesen Informationen zu erstellen. Außerdem werden für Studierende relevante Informationen zu den Hochschulpartnerschaften aus der Datenbank im Backend auf der Webseite angezeigt. 


=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.

=== Referenzen
Referentzen und Verweise werden - gegebenenfalls - an den benötigten Stellen eingefügt.

== Positionierung

=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

Das Projekt wird im Rahmen der Module Software Engineering I (I150) und II (I151) der Studiengänge Wirtschaftsinformatik, Verwaltungsinformatik, Wirtschaftsingenieurwesen und Informatik bearbeitet. 

Die Hochschulpartnerschaften und ihre Nutzung durch Studierende werden von den 
Mitarbeitern  der Stabsstelle Internationales verwaltet. Zu einer Hochschul-Partnerschaft 
gehören diverse Angaben zur Hochschule, Art der Vereinbarung, Kontakte, 
Mentoren etc. Dazu wird momentan von der Stabsstelle Internationales 
eine Microsoft Access-Datenbank genutzt. Damit ist jedoch der Mehrbenutzer-
betrieb nicht möglich und muss umständlich realisiert werden. Zudem sind bestimmte benötigte Funktionen wie das Löschen inkonsistenter oder veralteter Daten nicht ausreichend vorhanden. Daher wird das Ersetzten der Access-Datenbank und eine Bedinung durch eine Webanwendung angestrebt.

In Zukunft soll es den Mitarbeitern möglich sein, über diese Webanwendung die Daten neu anzulegen,
zu verändern bzw. zu löschen, welche durch eine Maria-Datenbank bereitgestellt werden. Mit dieser Erneuerung verspricht sich die Stabstelle Internationales verbesserte Benutzerfreundlichkeit sowie einen geringeren Arbeitsaufwand für die Pflege der Daten.

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Das Problem | einer unzureichenden Bedienbarkeit und hohe Fehleranfälligkeit
| betrifft | Mitarbeiter der Stabsstelle Internationales, Studentische Hilfskräfte (SHK) und Studierende, die sich über die Partnerschaften informieren wollen
| die Auswirkung davon ist | ein erhöhter und umständlicher Arbeitsaufwand in der Verwaltung  
| eine erfolgreiche Lösung wäre | ein neues Online-Datenbankverwaltungssystem für die
Hochschulpartnerschaften zur Pflege der Daten der Hochschul-Partnerschaften (Anlegen, Ändern, Löschen) und evtl. Weiterentwicklungsmöglichkeiten zu gewährleisten.

|===

////
Beispiel:
[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft | Studierende der HTW Dresden
|die Auswirkung davon ist | umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre | die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Für | Mitarbeiter der Stabsstelle Internationales, Studentische Hilfskräfte (SHK) und interessierte Externe (zB. Studierende, die sich über die Partnerschaften informieren wollen)
| die | die Verwaltung effizienter durchführen möchten bzw. die Einsicht freigegebener Daten für interessierte Externe leicht zugänglich zu machen. 
| Das Produkt ist eine | Webanwendung mit einer Schnittstelle zur Maria-Datenbank (Online-Datenbankverwaltungssystem)
| die | die Datenverwaltung für die Mitarbeiter, Informationsbeschaffung für die Studierenden zu Partneruniversiäten/Austauschprogrammen ermöglicht. 
| Im Gegensatz zu | der aktuell genutzten MS-Access-Datenbank 
| Unser Produkt | ermöglicht den Mehrbenutzerbetrieb für die Datenbank zu verwalten und Informationen daraus abzufragen bzw. hinzuzufügen.
|===

////
Beispiel Produkt:
|===
| Für | Studierende der HTW
| die | die ihren Studienalltag effizienter organisieren möchten
| Das Produkt ist eine | mobile App für Smartphones
| Die | für den Nutzer Informationen zum Stundenplan und Noten darstellt
| Im Gegensatz zu | Stundenplänen der Website und HIS-Noteneinsicht
| Unser Produkt | zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
|===
////


== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[cols="1,3,3"]
|===
|Stakeholder | Beschreibung | Zusammenhang zum Softwaresystem
| Mitarbeiter der SI und Studentische Hilfskräfte (SHK)
| Sind bei SI angestellt. Als Nutzer des Systens verwalten sie die Datenbank.
| Verwalten die Daten der DB über Webfrontend
| Austauschstudenten Incoming
| Sind Studierende von Partnerhochschulen und interessiert an einem Austauschprogramm an der HTW
| Informieren sich über Austauschprogramme an der HTW über Informationsfrontend
| Austauschstudenten Outgoing
| Sind Studierende der HTW und interessiert an einem Austauschprogramm an einer Partneruniversität der HTW
| Informieren sich über Austauschprogramme mit Partnerhochschulen über Informationsfrontend
| Rechenzentrum der HTW
| Mitarbeiter der HTW, die für die Administration der genutzten Server verantwortlich sind
| Sie ermöglichen die Einbindung des Systems in die Website der HTW Dresden und sind verantwortlich für die Instandhaltung der Datenbankserver 
| Externe | Informieren sich über Austauschprogramme | greifen Informationen über das Informationsfrontend ab
|===

=== Benutzerumgebung
//Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

////
Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.
////


==== Mitarbeiter Stabsstelle Internationales und Studentische Hilfskräfte (SHK)
• Mitarbeiter ist an einem Datenbankverwaltungsprozess interessiert, der intuitiv und aufwandsarm ist
• Datenverwaltung wird über die Webanwendung online erfolgen
• Datenverwaltung sollte für mehrere Mitarbeiter gleichzeitig erfolgen

==== Externe 

• müssen die für sie zu Austauschprogrammen bzw. Partnerhochschulen relevanten Informationen einsehen können
• Darstellung auf einer öffentlich zugänglichen Webseite der HTW Dresden (bisheriges Frontend)
• Beliebig viele der Studierenden sollen auf der Webseite Daten abfragen können 

== Produkt-/Lösungsüberblick

=== Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header, cols="4,1,4,1"]
|===
| Funktionalität | Priorität | Features | Geplantes Release
| System login 
| 7 
| soll den Nutzern per Authentifizierung den Zugang zum Verwaltungsfrontend gewähren 
| Sommersemester 2022

| Anlegen von Partnerhochschulen
| 10 
| Zum erzeugen neuer Partnerhochschulen im Verwaltungsfrontend
| Sommersemester 2022

| Bearbeiten von Hochschulen 
| 10 
| Zum anpassen eines oder mehrerer Hochschulattribute im Verwaltungsfrontend
| Sommersemester 2022

| Löschen von fehlerhaften Datensätzen
| 5 
| Zum löschen eines Datenbankattributes im Verwaltungsfrontend
| Sommersemester 2022

| Anlegen von Mentoren 
| 7
| Zum erzeugen neuer Mentoren im Verwaltungsfrontend
| Sommersemester 2022

| Bearbeiten von Mentoren 
| 7
| Zum anpassen eines Mentoren im Verwaltungsfrontend
| Sommersemester 2022

| Löschen von Mentoren
| 5 
| Zum löschen eines Mentoren im Verwaltungsfrontend
| Sommersemester 2022

| Erstellen von Berichten über Erasmusvereinbarungen
| 3 
| Zum Erstellen eines Berichtes im Verwaltungsfrontend
| Sommersemester 2022

| Erstellen von Berichten über Mentoren
| 3 
| Zum Erstellen eines Berichtes im Verwaltungsfrontend
| Sommersemester 2022

| Erstellen von Berichten über Hochschulvereinbarungen
| 3 
| Zum Erstellen eines Berichtes im Verwaltungsfrontend
| Sommersemester 2022

| Erstellen von Berichten über Abkommen nach Länder sortiert
| 3 
| Zum Erstellen eines Berichtes im Verwaltungsfrontend
| Sommersemester 2022

|===


== Zusätzliche Produktanforderungen
////
Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.
////

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release

| Detaillierte Entwicklerdokumentation für die Weiterentwicklung
| 7
| Sommersemester 2022

| Nutzerdokumentation für das Akedmisches Auslandsamt  
| 7 
| Sommersemester 2022

| Umsetzung der Lösung als Webanwendung 
| 10 
| Sommersemester 2022

| Soll in jedem modernen Browser nutzbar sein 
| 8 
| Sommersemester 2022

| einfache/intuitive Bedienbarkeit
| 7 
| Sommersemester 2022

|  Zugriff darf nur innerhalb des HTW Netzes erfolgen und wird durch eine IP-Sperre gewährleistet
|  10
| Sommersemester 2022

|  Personenbezogene Daten (sofern vorhanden) dürfen das System nicht verlassen und werden periodisch gelöscht. 
|  10
| Sommersemester 2022

|===
