= Architecture Notebook: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!


== Architekturziele und Philosophie
//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).
Der Zweck des Systems ist das Schaffen einer Webanwendung zum Verwalten von Hochschulpartnerschaften und Studenten-/Lehreraustausch. Benutzer
sollten die Anwendung auf Rechnern jeglicher Art (Laptop, Notebook, Desktop-Rechner) im Browser aufrufen können. Mobile Endgeräte sind dabei nicht
zu berücksichtigen. Die Erreichbarkeit des Systems ist sehr eingrenzbar, sie ist gebunden an die Arbeitszeiten der Stabsstelle Internationales
welche sich auf 8 Stunden, 7-15 Uhr, werktags beläuft. Außerhalb dieser Zeit gibt es keine Verpflichtung zur Erreichbarkeit.

Zur Unterstützung der schnellen Bearbeitung wurde sich beim Design des Interfaces stark an einem Prototyp und dem Arbeitsablauf der SI orientiert, intuitives arbeiten wird so ermöglicht. Daraus resultierend sind Vorschriften bezüglich Performance, bei Aufruf versteckter Seitenelemente oder Laden von Daten, sollten nicht mehr als 3 Sekunden vergehen.




== Annahmen und Abhängigkeiten
//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

=== Annahmen
. Nutzer sind Mitarbeiter der Stabsstelle Internationales
. Nutzer befinden sich, mit einer stabilen Internetverbindung und einem modernen Browser, im Netz der HTW
. Jeder Nutzer erlaubt das Ausführen von Javascript-Skripts innerhalb seines Browsers

=== Abhängigkeiten
. Wir sind abhängig vom Rechenzentrum der HTW
.. Unser Server läuft über eine, vom Rechenzentrum bereitgestellte, virtuelle Maschine und muss wochentags von 7-15 Uhr erreichbar sein
.. Die Administration unserer Datenbank erfolgt über das Rechenzentrum, somit muss ein verantwortlicher Mitarbeiter die Verwaltung der Logins übernehmen

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.


== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

=== Schichtenarchitektur

Dadurch ist es möglich dem Softwaresystem und den dazugehörigen Bestandteilen feste Aufgabenbereiche zuzuordnen.

. Datenbank
.. Speichern der Daten
.. Ändern der Bestandsdaten
. Schnittstelle zwischen Datenbank und Verwaltungsfrontend (Backend)
.. Auswerten Clientseitiger Anfragen
.. Lesen der Datenbankeinträge
.. Ausführen von Datenbankbefehlen
. Schnittstelle zum Nutzer (Frontend)
.. Abrufen der Bestandsdaten
.. Verändern, Löschen der vorhandenen Datenbankeinträge
.. Hinzufügen neuer Datensätze


=== Webtechnologien

Durch das Verwenden der aufgeführten Webtechnologien möchten wir eine Nutzung, unabhängig des Betriebssystems, ermöglichen. Die Anwendung soll des Weiteren ohne Installation bestimmter Tools, auf etablierten Browsern nutzbar sein, sowie die einfache Erweiterung durch spätere Arbeitsgruppen.

. CSS / Javascript / HTML
.. Weitverbreitete, allgegenwärtige Technologien zur Webentwicklung
.. Vorkenntnisse innerhalb der Gruppe

=== Serverseitige Programmierung mit Python

Es wurde sich in diesem Fall für Python entschieden, da durch das Framework 'Flask' die Serverseitige Programmierung sehr übersichtlich gehalten wird. Es ist sehr einfach möglich, URL-Pfade anzupassen oder zu erweitern. Des Weiteren bestand im Bezug auf Flask innerhalb des Teams vereinzelt Vorerfahrung.


=== Frameworks

Das Verwenden von Frameworks ist gerade in Gruppen mit wenig Vorerfahrung sehr von Vorteil, der Code bleibt übersichtlich und die Webentwicklung wird erheblich vereinfacht.

. jQuery (Javascript)
. Flask (Python)


== Architekturmechanismen
https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

=== Sicherheit
Durch den Bereich der Analyse und die Betrachtung des bereits vorhandenen Prototyps haben wir die Entscheidung getroffen die komplette Anwendung zu schützen. Dies passiert zum einen durch einen IP-Schutz, welcher außerhalb des Softwaresystems eingebettet wird, und durch die Implementierung von Mitarbeiteraccounts (SWFA-2). Diese Accounts werden innerhalb der Datenbank verwaltet. Um den Punkt (SWFA-3) zu realisieren wird diese Art von Nutzersystem benötigt, wir müssen uns somit aber keine Gedanken mehr zur Nutzerverwaltung machen, dies übernimmt die Datenbank für uns.

=== Persistente Daten
Die Anforderung (SWFA-1) machte uns darauf aufmerksam, dass unsere Daten persistent zu speichern sind. Uns blieb, aufgrund einiger Vorgaben, nichts anderes übrig als das bestehende Datenbankmodell zu übernehmen. Die Entscheidung wurde von Vorgängern getroffen, somit verwenden wir eine MariaDB welche vom Rechenzentrum gehostet wird.

=== Interface
In der Analyse wurde festgestellt das SWFA-3, die unterschiedliche Darstellung der Webseite je nach Nutzerrechten, ein wesentlicher Bestandteil des Projektes ist. Durch diesen Punkt sind wir auch zu dem Entschluss gekommen, unser Frontend nach dem Schema des responsive Webdesign zu entwerfen. Der Fakt dass es unterschiedliche Nutzer gibt, brachte die Analyse zu der Erkenntnis das die Endgeräte der jeweiligen Nutzer nicht den gleichen Voraussetzungen entsprechen. Unsere Website ist nun in der Lage sich dem Bildschirm des jeweiligen Endgerätes anzupassen, insofern es sich um ein Notebook, einen Laptop oder Desktop-PC handelt.


== Wesentliche Abstraktionen
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]


== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]


== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

Folgende Sichten werden empfohlen:

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.

=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante Anforderungne enthalten.
