= Projektbericht: {project-name} 
:project-name: Webanwendung zur Verwaltung von Hochschulpartnerschaften
// Settings:
:toc: 1
:toc-title: Inhaltsverzeichnis
:toclevels: 2
:sectnums: 1
:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:figure-caption: Abbildung
:table-caption: Tabelle
:!example-caption:
:experimental:
// folders
ifndef::imagesdir[:imagesdir: images]
ifndef::diagramsdir[:diagramsdir: diagrams]
ifndef::plantumlsdir[:plantumlsdir: plantuml]
// Hyphenation for PDF dokumente
:lang: DE
:hyphens:


// :docs: ../../docs

// include::{docs}/_includes/default-attributes.inc.adoc[]


// :doctype: book
// :toc:
// :toclevels: 2
// :toc-title: Inhaltsverzeichnis
// :sectnums:
// :icons: font
// //:source-highlighter: highlightjs
// :source-highlighter: rouge
// :rouge-style: github
// :xrefstyle: full
// :experimental:
// :chapter-label:
// :figure-caption: Abbildung
// :table-caption: Tabelle
// :listing-caption: Listing
// :!example-caption:
// :experimental:

// :imagesdir-reset: {imagesdir}

// :docs-test2: {docs}/test2
// :docs-requirements: {docs}/requirements
// :docs-project-management: {docs}/project_management
// :docs-architecture: {docs}/architecture
// :docs-test: {docs}/test
// :docs-development: {docs}/development


== Einführung (JH + JR)
Dieses Dokument enthält den Projektbericht zum Aufbau einer Hochschulpartnerschafts-Verwaltungs-Software im Rahmen des SE I und SE II Moduls des Teams I3.

== Planung (JH + JR)
=== Aufgabenstellung & Auftraggeber

Die Auftraggeber unseres Projektes "I3 Hochschulpartnerschaften Stabstelle Internationales" war die Stabstelle Internationales der HTW Dresden.
Die HTW Dresden kooperiert weltweit mit rund 170 Partnerhochschulen, um Studierenden die
Gelegenheit zu ermöglichen, sich kulturell weiterzubilden, neue Kontakte zu knüpfen und
Sprachkenntnisse zu vertiefen. Zu diesem Zweck werden die Informationen zu den Partnerhochschulen und Spezifikationen zu den bestehenden Verträgen mit diesen, sprich Anzahl an
Plätzen, Mentoren und verfügbare Fakultäten etc., sowie Daten über Incomings und Outgoings
gespeichert und verarbeitet. Genutzt wurde hierfür bis jetzt eine Access Datenbank.
Der Auftrag des Projektteams I3 bestand darin eine webbasierte Applikation mit Schnittstelle zu einer
Datenbank zu realisieren, die die Verwaltung der Hochschulen für die Mitarbeiter der Stabsstelle internationales vereinfacht. 

=== Situation zum Semesterbeginn

Zu Beginn des Semesters SS22 waren die Inception und Elaborationsphase des Projekts bereits
abgeschlossen (Software Engineering I). Außerdem konnte im vorherigen Semester bereits ein Prototyp der Software mit einigen grundlegenden Funktionen erstellt werden. 

=== Projektorganisation
==== Team & Rollen
Das Projektteam besteht aus 8 Mitgliedern, dessen größe über die Module SE I und SE II konstant blieb. 

• Project-Manager: Jakob Häcker (JH)
• Analyst: Nico Rosenkranz, Patrick Matthes  
• Architect: Pascal Thielemann
• Developer: Pascal Thielemann, Thanh Ha Khoung, Jens Rosenkranz (JR)
• Tester: Patrick Matthes, Roman Patzig
• Deployment Engineer: Luca Meißner
• Technical Writer: Thanh Ha Khoung, Jens Rosenkranz

==== Kommunikation

Aufgrund der vor allem im vorangegangenen Semester herrschenden Pandemie und des damit einhergehenden Onlinebetriebs an der Hochschule, hat sich für das ganze Projekt eine Kommukikation über Online-Videokonferenzen (Discord, Teams, BigBlue utton) sowie über Messenger (WhatsApp) etabliert. Zu keinem Zeitpunkt haben sich alle Teammitglieder in Präsenz getroffen.
Die Meetings mit dem Auftraggeber und dem Coach wurden ebenfalls remote druchgeführt und
fanden in sehr angemessenem Umfang regelmäßig statt (ca. alle 4 Wochen). Dank der Flexibilität von Online-Meetings konnten Termine zwischen den Teammitgliedern und auch mit dem Coach oder der Stabstelle konnten Termine auch kurzfirstig vereinabrt werden. 
Die Versionsverwaltung des Projektes wurde über ein Git-Repository realisiert, was ein gleichzeitiges Arbeiten aller Teammitglieder an dem Projekt ermöglichte.

===== Teaminterne Kommunikation
Um eine schnelle agile Kommunikation zwischen den einzelnen Gruppen bzw. Rollen innerhalb des Teams zu ermöglichen, wurden auf dem von Luca Meißner eingerichteten Discordserver für jede Rolle einzelne Untergruppen erzeugt.
Als Erweiterung, für schnelle, spontane Absprachen  wurde eine WhatsApp Gruppe erstellt.

===== Kommunikation mit unserem Coach
Termine mit dem Coach, Herrn Ringel, wurden über das HTW E-Mail System abgesprochen und über MS Teams abgehalten.

===== Kommunikation mit unseren Themenstellerinnen
Mit dem Themensteller, der Stabstelle Internationales, wurden Termine per E-Mail vereinbart und ebenso Dokumente geteilt.
Meetings wurden über einen, von der SI zur Verfügung gestellten, BBB Raum gehalten.

==== Projektaufgabenverwaltung
Die Aufgabenverwaltung hat das Team in SE I über GitHub Issues organisiert und eine übergeordnete Organisationsebene mit Git Projects etabliert.
Dies hat allerdings nur eingeschränkt funktioniert, da der Zugang zu den Git Projects sich für die Teammitglieder umständlich gestaltet hat und die Verwaltungsebene somit nicht ausreichend gepflegt wurde.
Weiterhin war es unpraktisch sämtliche Aufgaben in GitHub als Issues abzubliden, da diese auch für Aufgaben und Probleme völlig unterschiedlicher Größenordnung definiert wurden.
Dies hatte eine große Unübersichtlichkeit zur Folge, die eine strukturierte Handhabung der Issues unmöglich machte. Es war somit kaum Möglich den Fortschritt des Projekts zu veranschaulichen.
Abhilfe für diese Problem schaffte das in der Mitte des SE II Moduls eingführte Tool ZenHub.
Damit war es möglich Hirachien, Abhängigkeiten und den jeweiligen Arbeitsaufwand der Issues zu modellieren. Eine Visualisierung des Projektfortschrittes wurde zudem ebenfalls ermöglicht.

== Durchführung (JH + JR)

Zu Beginn des Sommersemesters SS22 hat sich das Team zu einer Online-Besprechung getroffen um sich den Ist-Zustand des Projekts zu verdeutlichen und einen Überblick über die noch zu bewältigenden Aufgaben und Probleme zu verschaffen. Als Grundlage für das weitere Vorgehen wurde einerseits die noch offenen Issues aus ZenHub und andererseits das Dokument "Belegarbeiten Prüfungsorganisation" herangezogen, welches durch Herrn Prof. Anke zur Verfügung gestellt wurde.  Daraufhin wurden die Verantwortlichkeiten für die Aufgaben und zu erstellenden Dokumente an die einzelnen Gruppen (Implementierung, Test, Projektleitung, etc.) verteilt und ein größtenteils eigenverantwortliches Arbeiten vereinbart. 


// oder besser nur Iterationen beschreiben?
// bzw beschreiben warum Iterationen eher schwammig waren (kein vorhandenes Inkrement bei manchen)
=== Inception

==== Ziele
==== Problem 
==== Ergebnisse

=== Elaboration
==== Ziele
==== Problem 
==== Ergebnisse

=== Construction
==== Ziele
==== Problem 
==== Ergebnisse

=== Transition
==== Ziele
==== Problem 
==== Ergebnisse


== Ergebnisse
=== Softwaresystem
==== Lizenz

=== Reflexion der Teammitglieder

==== Jakob Häcker
Das erstellen von komplexen Software Systemen, war für mich vor dem Modul Software Engineering nicht greifbar und somit hatte ich auch keine Vorstellung was es eigentlich bedeutet komplexe Software in Teamarbeit zu erstellen, geschweige denn was alles dafür nötig ist.
Eins blieb mir jedoch aus dem Fakultativen Modul von Frau Hauptmann - Soziale Kompetenzen im Projektmanagement - in Erinnerung.
Nämlich, dass ca. 50% der Softwareprojekte im Team an zwischen Menschlichen kompetenzen scheitern.
Inspieret von diesem Modul entschied ich mich als Projektleiter vorzuschalgen.
Was ich nicht wusste war, welche Verantwortung ich mir mit dieser Wahl auferlegte.

Zu beginn des ersten Semesters war zwar die Motivation hoch, allerdings viel es mir sehr schwer die vermittelten Konzepte der Vorlesung auf die Projekt realität zu adaptieren und anzuwenden. Die Hilfestellung OpenUp war für mich zu diesem Zeitpunkt auch eher unverständlich und da alles nur eine Empfehlung war wusste ich nicht viel damit anzufangen.
==== Thanh Ha Khuong

==== Patrick Matthes

==== Meißner Luca

==== Roman Patzig
Das Projekt „Verwaltung der Hochschulpartnerschaften“ in Zusammenarbeit mit der Stabsstelle Internationales der HTW Dresden war das erste komplexe Software-Projekt, in welchem ich von Anfang bis Ende mitwirken durfte. Daher hat es nicht nur mich, sondern auch uns als Team vor neuen Herausforderungen gestellt, welche uns allen zahlreiche Möglichkeiten geboten haben, unsere Fähigkeiten zu erweitern.

Trotz Vorkenntnisse im Bereich Projektmanagement hat das Projekt durch den Umfang, Größe des Teams sowie der Spezifität viel neues von mir abverlangt. Dies hat durch die Kontinuität des Projektes jedoch viele Vorteile gebracht – das Lernen neuer Programmiersprachen, das Arbeiten mit Selenium und somit auch erstmals automatisiertes Testen, das Arbeiten mit GitHub, welches nicht zuletzt auch für andere Module sehr praktisch war, und das Koordinieren im Team durch regelmäßige Meetings und Aufgabenverteilungen. 

Durch das Projekt konnte ich direkt anwendungsbezogen Einblicke in die Programmiersprache Phyton bekommen, was mir die dazugehörige Arbeit als Tester mit Selenium direkt erleichterte. Dadurch konnte ich zielgerichtet automatisierte Tests entwickeln, die auf derselben Programmiersprache laufen, wie die eigentliche Software. Dabei hat mir die Zusammenarbeit im Team sowie in kleineren Unterteams sehr gut gefallen, weil man sich jederzeit darüber austauschen konnte und Aufgaben gegebenenfalls auch aufteilen konnte.

Um das Projekt zu dokumentieren und zu analysieren, war dann GitHub zur Stelle. Nach einiger Eingewöhnungszeit sowie dem Einrichten mit der lokalen Entwicklungsumgebung war das Projekt startklar, jedoch wurde schnell klar, dass man übersichtlicher arbeiten müsse, um gegebenenfalls freie Ressourcen besser einplanen zu können. Also haben wir Issues angelegt und Aufgaben verteilt. Jedoch gab es nach wie vor Probleme mit dem Überblick, weshalb wir uns dann für die Erweiterung ZenHub entschieden haben. Dies hat es uns ermöglicht nicht nur die Dringlichkeit der Issues hervorzuheben, sondern auch intuitiv via Drag and Drop innerhalb einer Übersicht den Status zu verändern. Dies hat mir persönlich sehr gut gefallen und der Organisation im Team nochmals weitergeholfen.

Während meiner Arbeit als Analyst war ich dafür zuständig die jeweiligen Risiken zu erkennen, zu sortieren und letztlich auch einzuordnen. Hierfür hat sich die Arbeit mit der Risk_List als sehr hilfreich gezeigt – weil somit das gesamte Team einen Einblick über Risiken während des gesamten Projektverlaufes erhalten konnte und somit direkt den Problemen entgegengewirkt werden konnte, bevor sie überhaupt entstanden.

Durch das Projekt kann ich nun auch in zukünftigen Projekten die neu erworbenen persönlichen Fähigkeiten nutzen, um somit noch effizienter arbeiten zu können. Ich weiß nun auch wie wichtig es ist auf die Deadlines zu achten, damit andere Ihren Aufgaben nachgehen können und wie essenziell es ist diese nicht zu unterschätzen. Der Einblick in die Welt des Projektmanagements hat mich weitergebracht und auch in der längerfristigen Zusammenarbeit mit dem Team Freude bereitet.


==== Jens Rosenkranz
Das Projekt "Verwaltung der Hochschulpartnerschaften" der HTW Dresden war für mich das erste Softwareprojekt dieser Größe und Komplexität. Außerdem hatte ich bis dahin noch nicht mit so vielen Teilnehmern an einem Projekt zusammengearbeitet. Meine Erfahrung in der Softwareentwicklung beschränkte sich zum Anfang des Projekts ausschließlich auf die bisherigen Projekte des Studiums. Insbesondere hatte ich keinerlei Kenntnisse in der Programmierung von Webanwendungen, davon wie man Datenbanken mit einer Programmiersprache wie Python ansteuert oder wie man über ein Repository im Team programmiert. Insofern kann man sagen, dass meine Vorkenntnisse zum Projektbeginn sehr gering waren. Daher wollte ich ursprünglich eher die organisatorischen Aufgaben übernehmen und mich um die Ausgestaltung der Dokumente kümmern. Allerdings hat sich in der ersten Vorstellungsrunde der Teammitglieder herausgestellt, dass auch alle anderen Teammitglieder nahezu keine Vorkenntnisse hatten und ebenfalls eher organisatorische Aufgaben übernehmen wollten. Das hat dazu geführt, dass ich letztendlich die Rolle eines Entwicklers übernommen habe. Es hat sich also schnell abgezeichnet, dass ich mir sehr schnell sehr viel Wissen aneignen werden muss, um das Modul zu bestehen. Insbesondere während des dritten Semesters, also dem Projektbeginn, habe ich es als sehr große Herausforderung empfunden, neben dem Vorlesungsstoff noch zusätzlich selbstständig Programmierung in HTML, CSS und Javascript zu erlernen. Glücklicherweise hatte ein Teammitglied schon genug Vorkenntnisse, um das Projekt entwicklerseitig ins Rollen zu bringen. Im vierten Semester konnte ich mich mehr und mehr in die Entwicklung des Prototyps einbringen, da in diesem Semester die benötigten Kenntnisse innerhalb der verschiedenen Vorlesungen und Praktika vermittelt wurden. Zum Beispiel war Webprogrammierung ein Inhalt der Veranstaltung Internettechnologien und Datenbankprogrammierung Inhalt der Vorlesung Programmieren von Komponentenarchitekturen. 
Das Projekt war in jedem Fall der beste Beweis dafür, dass es absolut sinnvoll ist die Entwicklung einer komplexeren Anwendung im Team strukturiert anzugehen und sich im Vorfeld darüber klar zu werden, was der Kunde genau will und was man in der Lage ist tatsächlich umzusetzen, wer welche Aufgabe und Verantwortung hat und was man bis zu welchem Zeitpunkt erledigt haben will. Mir hat insbesondere das agile Vorgehen gut gefallen, da wir erst nach und nach durch mehrere Meetings mit dem Kunden verschiedenste Missverständnisse ausräumen konnten. Hätten wir nur vorab die Anforderungen und Wünsche mit den Kunden besproche, wäre am Ende sehr sicher nicht das dabei herausgekommen, was sich der Kunde vorgestellt hat. 
Die Zusammenarbeit mit unserem Kunden, der Stabstelle Internationales an der HTW, war insgesamt gut, auch wenn wir regelmäßig Erwartungshaltungsmanagement betreiben mussten. Die SI ist uns in vielen Punkten entgegengekommen und hat unserem Team gegenüber viel Geduld und Verständnis gezeigt. Die Zusammenarbeit mit einem echten Kunden, war sehr lehrreich. Es war ein Prozess zu verstehen, was der Kunde genau möchte und ebenso zu vermitteln, was wir zu liefern in der Lage sind. Das in einem realistischen Szenario üben zu können, war eine super Erfahrung. 
Genauso war es eine herausfordernde und lehrreiche Erfahrung in einem Team von acht Kommilitonen zusammenzuarbeiten. Nachdem anfänglich große Unsicherheit wegen der fehlenden Kenntnisse herrschte, hat sich nach einigen Wochen eine relativ gute Arbeitsteilung zwischen den meisten Teammitgliedern ergeben. Trotz des spürbaren Drucks durch das Projekt und das Studium im allgemeinen, sind nur wenige Konflikte entstanden und diese konnten zur Zufriedenheit aller gelöst werden. Die Teammitglieder waren größtenteils sehr motiviert und haben ihre Rollen und Aufgaben verantwortungsvoll erfüllt. Durch das Projekt "Verwaltung von Hochschulpartnerschaften" konnte ich zum ersten mal die
unterschiedlichen Phasen einer agilen Software Entwicklung innerhalb eins  Teams erleben. Die Aufteilung eines komplexen Softwareprojekts in Teilbereiche, die Analyse, Modellierung und schließlich die Implementierung im Team mittels GitHub waren neu für mich und haben Spaß gemacht.
Ich habe durch das Projekt viel gelernt und die erste echte Erfahrung in Softwareentwicklung gemacht. 


==== Nico Rosenkranz
==== Pascal Thielemann


