include::../_includes/default-attributes.inc.adoc[]

= Projektbericht: {project-name} 

// :imagesdir-reset: {imagesdir}
// :docs-test2: {docs}/test2
// :docs-requirements: {docs}/requirements
// :docs-project-management: {docs}/project_management
// :docs-architecture: {docs}/architecture
// :docs-test: {docs}/test
// :docs-development: {docs}/development


== Einführung (JH + JR)
Dieses Dokument enthält den Projektbericht über die Erstellung der Webanwendung zur Verwaltung der Hochschulpartnerschaften und Austauschprogramme. Das Projekt wurde im Rahmen des SE I und SE II Moduls des Teams I3 durchgeführt.

== Planung (JH + JR)
=== Aufgabenstellung & Auftraggeber

Die Auftraggeber unseres Projektes "I3 Hochschulpartnerschaften Stabstelle Internationales" war die Stabstelle Internationales der HTW Dresden.
Die HTW Dresden kooperiert weltweit mit rund 170 Partnerhochschulen, um Studierenden die
Gelegenheit zu ermöglichen, sich kulturell weiterzubilden, neue Kontakte zu knüpfen und
Sprachkenntnisse zu vertiefen. Zu diesem Zweck werden die Informationen zu den Partnerhochschulen und Spezifikationen zu den bestehenden Verträgen, zB. Anzahl an verfügbaren
Plätzen, Mentoren und verfügbare Fakultäten etc., sowie Daten über Incomings und Outgoings
gespeichert und verarbeitet. Genutzt wurde hierfür bis jetzt eine Access Datenbank.
Der Auftrag des Projektteams I3 bestand darin eine webbasierte Applikation mit Schnittstelle zu einer
Datenbank zu realisieren, die die Verwaltung der Hochschulen für die Mitarbeiter der Stabsstelle internationales vereinfacht. 

=== Situation zum Semesterbeginn

Zu Beginn des Semesters SS22 waren die Inception und Elaborationsphase des Projekts bereits
abgeschlossen (Software Engineering I). Außerdem konnte im vorherigen Semester bereits ein Prototyp der Software mit einigen grundlegenden Funktionen erstellt werden. 

=== Projektorganisation
==== Team & Rollen
Das Projektteam besteht aus 8 Mitgliedern, dessen Größe über die Module SE I und SE II konstant geblieben sind. 

• Project-Manager: Jakob Häcker (JH)
• Analyst: Nico Rosenkranz (NR), Patrick Matthes  (PM) 
• Architect: Pascal Thielemann (PT)
• Developer: Pascal Thielemann, Thanh Ha Khuong (HK), Jens Rosenkranz (JR)
• Tester: Patrick Matthes, Roman Patzig (RP)
• Deployment Engineer: Luca Meißner (LM)
• Technical Writer: Thanh Ha Khuong, Jens Rosenkranz

==== Kommunikation

Aufgrund der vor allem im vorangegangenen Semester herrschenden Pandemie und des damit einhergehenden Onlinebetriebs an der Hochschule, hat sich für das ganze Projekt eine Kommukikation über Online-Videokonferenzen (Discord, Teams, BigBlueButton) sowie über den Messenger (WhatsApp) etabliert. Zu keinem Zeitpunkt haben sich alle Teammitglieder in Präsenz getroffen.
Die Meetings mit dem Auftraggeber und dem Coach wurden ebenfalls remote druchgeführt und
fanden regelmäßig (ca. alle 4 Wochen) statt. Dank der Flexibilität von Online-Meetings konnten Termine zwischen den Teammitgliedern, Meetings mit dem Coach oder mit der Stabstelle Internationales auch kurzfirstig vereinabrt werden.
Die Versionsverwaltung des Projektes wurde über ein GitHub-Repository realisiert, was ein komfortables gleichzeitiges Arbeiten aller Teammitglieder an dem Projekt ermöglichte.

===== Teaminterne Kommunikation
Um eine schnelle und agile Kommunikation zwischen den einzelnen Gruppen bzw. Rollen innerhalb des Teams zu ermöglichen, wurden auf dem von Luca Meißner eingerichteten Discordserver für jede Rolle einzelne Untergruppen erzeugt.
Als Erweiterung, für schnelle, spontane Absprachen  wurde eine WhatsApp Gruppe erstellt.

===== Kommunikation mit unserem Coach
Termine mit unserem Coach, Herrn Ringel, wurden über das HTW E-Mail System abgesprochen und über MS Teams abgehalten.

===== Kommunikation mit unseren Themenstellerinnen
Mit den Themenstellenden, die Stabstelle Internationales, wurden Termine per E-Mail vereinbart und aufgleichen Wege Dokumente geteilt.
Meetings wurden über einen, von der SI zur Verfügung gestellten, BBB Raum gehalten.

==== Projektaufgabenverwaltung und eingesetzte Tools

===== Aufgabenverwaltung

Die Aufgabenverwaltung hat das Team in SE I über GitHub Issues organisiert und eine übergeordnete Organisationsebene mit Git Projects etabliert.
Dies hat allerdings nur eingeschränkt funktioniert, da der Zugang zu den Git Projects sich für die Teammitglieder umständlich gestaltet hat und die Verwaltungsebene somit nicht ausreichend gepflegt wurde.
Weiterhin war es unpraktisch sämtliche Aufgaben in GitHub als Issues abzubliden, da diese auch für Aufgaben und Probleme völlig unterschiedlicher Größenordnung definiert wurden.
Dies hatte eine große Unübersichtlichkeit zur Folge, die eine strukturierte Handhabung der Issues unmöglich machte. Es war somit kaum Möglich den Fortschritt des Projekts zu veranschaulichen.
Abhilfe für diese Problem schaffte das in der Mitte des SE II Moduls eingführte Tool ZenHub.
Damit war es möglich Hirachien, Abhängigkeiten und den jeweiligen Arbeitsaufwand der Issues zu modellieren. Eine Visualisierung des Projektfortschrittes wurde zudem ebenfalls ermöglicht.

===== Protokollierung

Um die Ergebnisse und Erkenntnisse aus den Team-Meetings sowie den Meetings mit dem Coach und den Themenstellenden festhalten zu können, haben wir das online Toll Pentapad verwendet. Dieses erlaubt es allen Teilnehmern kollaborativ während der Meetings ein gemeinsames Protokoll anzufertigen. Dies hat sich als sehr Vorteilhaft herausgestellt, da durch die gemeinsame Mitschrift alle Ergebnisse der Meetings notiert werden konnten und auch sofort allen zur Verfügung standen.

===== Team-Regeln

Im laufe des Projektes wurden Regeln für die Teamarbeit auf gestellt.
Diese waren zunächst lose Vereinbarungen ohne wirkliche Wirkung.
Mit wachsender Komplexität des Projektes wurde es allerdings nötig diese schriftlich Fest zuhalten.
Dies wurde besonders Wirksam als das neue Tool ZenHub eingeführt wurde, da dies eine doch sehr weitreichende Umstellung mitten im Projekt war und somit klar Umrissene Handlungswiesen verlangte, wie zum Beispiel wann gehöhren Issues in welche ZenHub Pipline, wann ist ein ToDo ein Issue, wann ein übergeordnetes Issue (Epic), etc. .
Zusätzlich war es das Ziel der Regelen, durch eine einheitliche Grundlage an Verhaltensweisen, Kommunikationsaufwand zu sparen, eine klarere Struktur in der Verzeichnisherachie des Repositories zuschaffen und bestimmte Prozesse wie das Protokollieren und Planen der Iterationen zu rutinieren um so Zeit für wichtigere Dinge zu haben.

== Durchführung (JH + JR)

Zu Beginn des Sommersemesters SS22 hat sich das Team zu einer Online-Besprechung getroffen um sich den Ist-Zustand des Projekts zu verdeutlichen und einen Überblick über die noch zu bewältigenden Aufgaben und Probleme zu verschaffen.
Als Grundlage für das weitere Vorgehen wurden einerseits die noch offenen Issues und andererseits das Dokument "Belegarbeiten Prüfungsorganisation" herangezogen, welches durch Herrn Prof. Anke zur Verfügung gestellt wurde.
Daraufhin wurden die Verantwortlichkeiten für die Aufgaben und die zu erstellenden Dokumente an die einzelnen Gruppen bzw. Rollen (Implementierung, Test, Projektleitung, etc.) verteilt und ein eigenverantwortliches Arbeiten innerhalb dieser kleineren Teams vereinbart. 


// oder besser nur Iterationen beschreiben?
// bzw beschreiben warum Iterationen eher schwammig waren (kein vorhandenes Inkrement bei manchen)
=== Inception

In der Inception Phase haben sich die Teammitglieder zum ersten mal kennengelernt. Auf Grund der Corona-Pandemie und des damit einhergehenden generellen Online-Modus haben sich die Teammitglieder ausschließlich über zunächst verschiedene Tools (Teams, BBB, Discord) online getroffen. Da die meisten Teammitglieder ohnehin Discord als Kommunikationstool nutzten, hat Luca Meißner einen Discord-Server für das Projekt eingerichtet und hat sich für die restliche Projektdauer um die Verwaltung des Servers gekümmert.
Innerhalb der ersten Vorstellungsrunde haben die Teammitglieder ihre projektrelevanten Vorkenntnisse und ihre bevorzugten Rollen für das Projekt genannt. Dabei hat sich herausgestellt, dass bis auf einen, kein Teammitglied Vorkenntnisse in der Erstellung von Softwareprodukten dieser Größe hatten und sich nicht in der Lage sahen die Rollen Architect, Developer der Tester zu erfüllen. Trotz dieser anfänglichen Hürde konnten letztendlich alle Rollen in gegenseitigem Einverständnis besetzt werden. Beim ersten Meeting wurde auch vereinabrt wöchentliche Teammeetings abzuhalten um jeweils die anstehenden Aufgaben und den Ist-Zustand des Projekts zu besprechen. 
Um sich einen Überblick über die Projektaufgabe zu verschaffen, haben sich die Teammitglieder darauf geeinigt sich selbstständig in die von Herrn Prof. Anke bzw. vom Themensteller sowie der Vorgruppe bereitgestellten Dokumente zu lesen und für sich Fragen zu formulieren. Außerdem wurden bereits die ersten Treffen mit dem Coach und den Themenstellern vereinbart. Damit die Teammitglieder gemeinsam an der Software und den Dokumenten arbeiten konnten hat Jakob Häcker ein GitHub Repository erstellt, welches für die gesamte Dauer des Projekts weiterverwendet wurde.
Auf Basis der Aufgabenstellung und ersten Gesprächen mit den Themenstellern konnte eine Vision für das Projekt erstellt werden. Ebenso wurde für die ersten beiden Phasen des Projekts eine Risklist mit den zentralen Projektrisiken  erstellt. Die Teammitglieder haben sich dabei gemeinsam über GitHub an den Dokumenten gearbeitet, da bezüglich der korrekten Ausführung noch große Unsicherheit herrschte. 
Es stellte sich früh heraus das Pascal Thielemann hinsichtlich der Software Entwicklung über die meisten Kenntnisse verfügte. Daher hat sich das Team entschieden ihm die Entscheidung über die einzusenden IDE und die Softwarearchitektur überlassen. Generell wurden Entscheidungen demokratisch entschieden, wobei denjenigen die Entscheidung überlassen wurde, die zu der jeweiligen Fragestellung bereits Kenntnisse hatten. Innerhalb der wöchentlichen Teammeetings wurden Aufgaben gesammelt und protokolliert. Bevor das Meeting jeweils geschlossen wurde, wurden die Aufgaben verteilt bis für jede ein Verantwortlicher feststand.


==== Ziele
* Team verteilt Rollen und Aufgaben
* Das Visionsdokument beginnen
* Iterationsplan für die erste Iteration Inception erstellen
* Das Glossar beginnen und ab sofort pflegen
* Eine Risklist erstellen
* Kontakt zu Aufgabenstellern und Coach herstellen
* Terminfindung für wöchentliche Meetings der Teammitglieder

==== Problem 

===== Terminfindung
Es hat sich als sehr schwierig herausgestellt einen Termin zu für das wöchentliche Teammeeting zu finden. Um dieses Problem zu lösen wurde zunächst eine Exceltabelle mit den einer Art Kalender erstellt, in den alle Teammitglieder ihre Verfügbarkeiten eingetragen haben. Die Verfügbarkeiten wurden dann abgeglichen und auf Überschneidungen untersucht. Mit dieser Methode konnte kein gemeinsamer Termin gefunden werden. Um den Abgleich agile zu gestalten, wurde das online-Tool doodle verwendet und ein erneuter Versuch gestartet. Nachdem auch das nicht funktioniert hat, hat man sich auf einen Termin geeinigt an dem die meisten Teammitglieder Zeit hatten. Für diejenigen, die an den Meetings nicht live teilnehmen konnten, wurden ausführliche Protokollen angefertigt und nachträglich Telefonate mit einzelnen Teammitgliedern geführt, um jeden auf den neuesten Stand zu bringen.

===== geringe Programmierkenntnise

Da nur Pascal Thielemann nennenswerte Vorkenntisse in der Programmierung von Webanwendung hatte, hat das Team schon früh ein Scheitern des Projekts befürchtet. Daher haben sich die Teammitglieder Ha Khuong und Jens Rosenkranz frühzeitig mit dem Erlernen von CSS, HTML, Java Script und Python beschäftigt um langfristig bei der Softwareerstellung unterstützen zu können.

===== Arbeit in Rollen

Die Arbeit strikt nach den vorgegebenen Rollen hat sich anfänglich besonder schwierig gestaltet, da nicht klar wann wer welche Aufgaben zu erledigen hat und worin die Aufgaben von zum Beispiel Testern am Anfang des Projekt bestehen. Das Team hat sich daher darauf geeinigt die Rollenverteilung als Verantwortlichkeiten zu betrachten. Wer eine Rolle inne hat, ist nicht allein für den Bereich verantwortlich und arbeitet auch nicht nur an der Aufgaben dieser Rollen, sonder ist lediglich Ansprechpartner und behält den Überblick über die zu erledigenden Aufagaben welche ebenfalls durch den Rolleninhaber an alle Teammitglieder delegiert werdne.

==== Ergebnisse

In der Iterationsphase konnten nach anfänglichen Schwierigkeiten gute Fortschritte erreicht werden. Es herrschte Einigkeit über die Rollenverteilung, geeignete Tools zur Kommunikation mit sämtlichen Akteuern waren gefunden und die Infrastruktur zum kollaborativen Arbeiten war bereitgestellt. Außerdem konnten die zum Projektbeginn benötigten Dokumente, wie die Vision und die Risklist erfolgreich begonnen werden. Ebenso konnte Pascal Thielemann mit den ersten Zeilen Code ein "proof of concept" liefern und unter Beweis stellen, dass die von ihm Gewählten Programmiersprachen sich für die Durchführung des Projekts eigneten.

=== Elaboration
==== Ziele

==== Problem 
==== Ergebnisse

=== Construction
==== Ziele
==== Problem 
==== Ergebnisse

=== Transition
==== Ziele
==== Problem 
==== Ergebnisse


== Ergebnisse
=== Softwaresystem
==== Lizenz

=== Reflexion der Teammitglieder

==== Jakob Häcker
Das erstellen von komplexen Software Systemen, war für mich vor dem Modul Software Engineering nicht greifbar und somit hatte ich auch keine Vorstellung was es eigentlich bedeutet komplexe Software in Teamarbeit zu erstellen, geschweige denn was alles dafür nötig ist.
Eins blieb mir jedoch aus dem Fakultativen Modul von Frau Hauptmann - Soziale Kompetenzen im Projektmanagement - in Erinnerung.
Nämlich, dass ca. 50% der Softwareprojekte im Team an zwischen Menschlichen kompetenzen scheitern.
Inspieret von diesem zusatz Modul entschied ich mich als Projektleiter vorzuschalgen.
//Was ich nicht wusste war, welche Verantwortung ich mir mit dieser Wahl auferlegte.

Was ich hauptsächlich aus der Projekt arbeit mitnehme:
1) Mann muss Entscheidungen fällen auch wenn sie sich höchstwahrscheinlch in naher Zukunft als falsch erweisen.
- geht im allgemeinen darum das man lernen muss die Angst vor wichtigen entscheidungen ablegt und lieber etwas zu entscheiden als garnichts zu entscheiden
- schein bar simpel aber ohne es Erlbt zu haben weiß man nicht wirklich was der Satz tatsächlich bedeutet
- ist in dem Projekt kontext sehr wichtig dass verstanden zu haben, da sonst viel zeit verloren geht und man auch keine grundlage hat die man verbessern kann. 
- auch zwingt es einen 

2) Was es bedeutet verantwortung zu übernehemen
- entscheidungen fällen
- ansprech partner für alle zu sein (hat mir viel freude bereitet)



Am Anfang des Projektes wurde ich von der Freiheit in der Gestaltung der Projektorganisation sehr überrascht.
Es viel mir schwerer als Gedacht grundlegende Entscheidungen zu treffen deren Folgen absolut ungewiss sind und die Vorlesungsinhalte auf die Projektrealität zu adaptieren.
Rückblickend war mir anfänglich auch nicht Bewusst, wie wichtig die entscheidungen in der ersten Projetk phase sind.
Somit war ich auch eher Halbherzig bei der Sache und habe die Hilfestellungen (zB OpenUP) zu wenig verwendet.
Nicht zu letzt des Wegen, da ich nicht wirklich wusste mit ihnen umzugehen und mir die Konzepte dort aus irgendwelchen gründen ziemlich Abstrakt wirken (mit der jetzigen Erfahrung ist dies natürlich nicht mehr so wodurch ich mein Handeln auch nicht mehr Nachvollziehen kann).

==== Thanh Ha Khuong
Das Projekt „Verwaltung von Hochschulpartnerschaften“ in Kooperation mit dem International Office der HTW Dresden war nicht nur für mich, sondern auch für die meisten meiner Teammitglied das erste komplexe Großprojekt. Ich freue mich, Teil des Teams zu sein und zum Softwareentwicklungsprozess beizutragen. Ich habe durch dieses Projekt viele Dinge gelernt, insbesondere wie die Software aufgebaut ist und wie man mit anderen Menschen zusammenarbeitet.

Trotz der Herausforderungen und des holprigen Starts freue ich mich, dass unser Team das Projekt abschließen kann. Zu Beginn der Projekte standen wir vor vielen Herausforderungen, wie z. B. fehlenden technischen und organisatorischen Fähigkeiten. Das Management hat sich von Anfang bis Ende stark verbessert. Die Kommunikation ist viel effizienter, da sich das Team regelmäßiger trifft, um das laufende Thema zu besprechen, Aufgaben aufzuteilen und zu verfolgen und Missverständnisse auszuräumen. Die Organisation der Aufgaben ist mit GitHub viel übersichtlicher, sodass jeder den Überblick hat, wer für welche Aufgaben zuständig ist. Wir haben insgesamt einen strukturierteren Arbeitsablauf. Ich genieße es auch, das Subteam in 2-3 Personen aufzuteilen, da wir uns mehr auf bestimmte Aufgaben konzentrieren und uns bei Bedarf gegenseitig helfen können.
Außerdem haben wir einen echten Kunden, mit dem wir zusammenarbeiten können. Am Anfang holten wir die Ideen nur langsam ein, aber die Kunden waren sehr geduldig und führten uns freundlich durch. Es war eine Herausforderung, einen Termin mit dem achtköpfigen Team und den Kunden zu vereinbaren, aber schließlich konnten wir uns abstimmen und uns regelmäßig treffen.

Das Projekt hat mir anwendungsbezogene Einblicke in die Programmiersprache Python und das Flask-Framework gegeben. Ich habe auch die Möglichkeit, meine Kenntnisse in HTML, CSS und der Bootstrap-Bibliothek anzuwenden, um die Schnittstelle zu erstellen. Ich lerne auch, wie das Softwareprogramm aufgebaut ist und wie man den Code versteht und dokumentiert. Ich verstehe jetzt, wie wichtig sauberer, verständlicher Code für ein Softwareprojekt ist. Ich hoffe, dass das nächste Team von unsere Prototyp profitieren kann.

Das Projekt hat mir aufgrund des Umfangs und der Größe des Teams viel Neues abverlangt. Durch die Projekte habe ich gelernt, dass es nicht reicht, nur meinen Teil Gutes zu tun, sondern auch einen Überblick über das Projekt zu haben. Außerdem müssen wir gut kommunizieren, um das Projekt zum Erfolg zu führen. Ich bin stolz darauf, von Anfang bis Ende zum Projekt beizutragen. Ich habe durch dieses Projekt in einem sicheren Raum viele Dinge gelernt. Dies ist eine wirklich schöne Gelegenheit für mich, einen Einblick in die Welt des Software Engineering zu bekommen.

==== Patrick Matthes

==== Meißner Luca

==== Roman Patzig
Das Projekt „Verwaltung der Hochschulpartnerschaften“ in Zusammenarbeit mit der Stabsstelle Internationales der HTW Dresden war das erste komplexe Software-Projekt, in welchem ich von Anfang bis Ende mitwirken durfte. Daher hat es nicht nur mich, sondern auch uns als Team vor neuen Herausforderungen gestellt, welche uns allen zahlreiche Möglichkeiten geboten haben, unsere Fähigkeiten zu erweitern.

Trotz Vorkenntnisse im Bereich Projektmanagement hat das Projekt durch den Umfang, Größe des Teams sowie der Spezifität viel neues von mir abverlangt. Dies hat durch die Kontinuität des Projektes jedoch viele Vorteile gebracht – das Lernen neuer Programmiersprachen, das Arbeiten mit Selenium und somit auch erstmals automatisiertes Testen, das Arbeiten mit GitHub, welches nicht zuletzt auch für andere Module sehr praktisch war, und das Koordinieren im Team durch regelmäßige Meetings und Aufgabenverteilungen. 

Durch das Projekt konnte ich direkt anwendungsbezogen Einblicke in die Programmiersprache Phyton bekommen, was mir die dazugehörige Arbeit als Tester mit Selenium direkt erleichterte. Dadurch konnte ich zielgerichtet automatisierte Tests entwickeln, die auf derselben Programmiersprache laufen, wie die eigentliche Software. Dabei hat mir die Zusammenarbeit im Team sowie in kleineren Unterteams sehr gut gefallen, weil man sich jederzeit darüber austauschen konnte und Aufgaben gegebenenfalls auch aufteilen konnte.

Um das Projekt zu dokumentieren und zu analysieren, war dann GitHub zur Stelle. Nach einiger Eingewöhnungszeit sowie dem Einrichten mit der lokalen Entwicklungsumgebung war das Projekt startklar, jedoch wurde schnell klar, dass man übersichtlicher arbeiten müsse, um gegebenenfalls freie Ressourcen besser einplanen zu können. Also haben wir Issues angelegt und Aufgaben verteilt. Jedoch gab es nach wie vor Probleme mit dem Überblick, weshalb wir uns dann für die Erweiterung ZenHub entschieden haben. Dies hat es uns ermöglicht nicht nur die Dringlichkeit der Issues hervorzuheben, sondern auch intuitiv via Drag and Drop innerhalb einer Übersicht den Status zu verändern. Dies hat mir persönlich sehr gut gefallen und der Organisation im Team nochmals weitergeholfen.

Während meiner Arbeit als Analyst war ich dafür zuständig die jeweiligen Risiken zu erkennen, zu sortieren und letztlich auch einzuordnen. Hierfür hat sich die Arbeit mit der Risk_List als sehr hilfreich gezeigt – weil somit das gesamte Team einen Einblick über Risiken während des gesamten Projektverlaufes erhalten konnte und somit direkt den Problemen entgegengewirkt werden konnte, bevor sie überhaupt entstanden.

Durch das Projekt kann ich nun auch in zukünftigen Projekten die neu erworbenen persönlichen Fähigkeiten nutzen, um somit noch effizienter arbeiten zu können. Ich weiß nun auch wie wichtig es ist auf die Deadlines zu achten, damit andere Ihren Aufgaben nachgehen können und wie essenziell es ist diese nicht zu unterschätzen. Der Einblick in die Welt des Projektmanagements hat mich weitergebracht und auch in der längerfristigen Zusammenarbeit mit dem Team Freude bereitet.


==== Jens Rosenkranz
Das Projekt "Verwaltung der Hochschulpartnerschaften" der HTW Dresden war für mich das erste Softwareprojekt dieser Größe und Komplexität. Außerdem hatte ich bis dahin noch nicht mit so vielen Teilnehmern an einem Projekt zusammengearbeitet. Meine Erfahrung in der Softwareentwicklung beschränkte sich zum Anfang des Projekts ausschließlich auf die bisherigen Projekte des Studiums. Insbesondere hatte ich keinerlei Kenntnisse in der Programmierung von Webanwendungen, davon wie man Datenbanken mit einer Programmiersprache wie Python ansteuert oder wie man über ein Repository im Team programmiert. Insofern kann man sagen, dass meine Vorkenntnisse zum Projektbeginn sehr gering waren. Daher wollte ich ursprünglich eher die organisatorischen Aufgaben übernehmen und mich um die Ausgestaltung der Dokumente kümmern. Allerdings hat sich in der ersten Vorstellungsrunde der Teammitglieder herausgestellt, dass auch alle anderen Teammitglieder nahezu keine Vorkenntnisse hatten und ebenfalls eher organisatorische Aufgaben übernehmen wollten. Das hat dazu geführt, dass ich letztendlich die Rolle eines Entwicklers übernommen habe. Es hat sich also schnell abgezeichnet, dass ich mir sehr schnell sehr viel Wissen aneignen werden muss, um das Modul zu bestehen. Insbesondere während des dritten Semesters, also dem Projektbeginn, habe ich es als sehr große Herausforderung empfunden, neben dem Vorlesungsstoff noch zusätzlich selbstständig Programmierung in HTML, CSS und Javascript zu erlernen. Glücklicherweise hatte ein Teammitglied schon genug Vorkenntnisse, um das Projekt entwicklerseitig ins Rollen zu bringen. Im vierten Semester konnte ich mich mehr und mehr in die Entwicklung des Prototyps einbringen, da in diesem Semester die benötigten Kenntnisse innerhalb der verschiedenen Vorlesungen und Praktika vermittelt wurden. Zum Beispiel war Webprogrammierung ein Inhalt der Veranstaltung Internettechnologien und Datenbankprogrammierung Inhalt der Vorlesung Programmieren von Komponentenarchitekturen. 
Das Projekt war in jedem Fall der beste Beweis dafür, dass es absolut sinnvoll ist die Entwicklung einer komplexeren Anwendung im Team strukturiert anzugehen und sich im Vorfeld darüber klar zu werden, was der Kunde genau will und was man in der Lage ist tatsächlich umzusetzen, wer welche Aufgabe und Verantwortung hat und was man bis zu welchem Zeitpunkt erledigt haben will. Mir hat insbesondere das agile Vorgehen gut gefallen, da wir erst nach und nach durch mehrere Meetings mit dem Kunden verschiedenste Missverständnisse ausräumen konnten. Hätten wir nur vorab die Anforderungen und Wünsche mit den Kunden besproche, wäre am Ende sehr sicher nicht das dabei herausgekommen, was sich der Kunde vorgestellt hat. 
Die Zusammenarbeit mit unserem Kunden, der Stabstelle Internationales an der HTW, war insgesamt gut, auch wenn wir regelmäßig Erwartungshaltungsmanagement betreiben mussten. Die SI ist uns in vielen Punkten entgegengekommen und hat unserem Team gegenüber viel Geduld und Verständnis gezeigt. Die Zusammenarbeit mit einem echten Kunden, war sehr lehrreich. Es war ein Prozess zu verstehen, was der Kunde genau möchte und ebenso zu vermitteln, was wir zu liefern in der Lage sind. Das in einem realistischen Szenario üben zu können, war eine super Erfahrung. 
Genauso war es eine herausfordernde und lehrreiche Erfahrung in einem Team von acht Kommilitonen zusammenzuarbeiten. Nachdem anfänglich große Unsicherheit wegen der fehlenden Kenntnisse herrschte, hat sich nach einigen Wochen eine relativ gute Arbeitsteilung zwischen den meisten Teammitgliedern ergeben. Trotz des spürbaren Drucks durch das Projekt und das Studium im allgemeinen, sind nur wenige Konflikte entstanden und diese konnten zur Zufriedenheit aller gelöst werden. Die Teammitglieder waren größtenteils sehr motiviert und haben ihre Rollen und Aufgaben verantwortungsvoll erfüllt. Durch das Projekt "Verwaltung von Hochschulpartnerschaften" konnte ich zum ersten mal die
unterschiedlichen Phasen einer agilen Software Entwicklung innerhalb eins  Teams erleben. Die Aufteilung eines komplexen Softwareprojekts in Teilbereiche, die Analyse, Modellierung und schließlich die Implementierung im Team mittels GitHub waren neu für mich und haben Spaß gemacht.
Ich habe durch das Projekt viel gelernt und die erste echte Erfahrung in Softwareentwicklung gemacht. 


==== Nico Rosenkranz
==== Pascal Thielemann


